### PR TITLE
onboarding wip

### PR DESCRIPTION
**Pull request by jdriscoll98**

### CODE REVIEW

**Comment by jdriscoll98** [comment]
It's a bit buggy like @KyleStrout said. I think we can make it easier for the user to navigate the issues though. For example, instead of the "click here to install metmask" button taking them directly to the chrome store, it should navigate to a page on our site that has a "guide" for installing metamask. 

That page can have another button that says "Start onboarding process" which will take them to the store, have them make the account ( this part works great ). 

When they finish, they will naturally come back to the page and the guide can have next steps to make sure they don't get stuck.

**Comment by jdriscoll98** [comment]
@KyleStrout @CWilson123 @colinnaehr  Can you guys test this page in a fresh browser ( no meta mask installed ? )

**Comment by KyleStrout** [comment]
This is really well done! Great job Jack!

Seems to have same issue that I had but the content is super helpful.

**Review by KyleStrout — APPROVED** [review]
Awesome

**Pull request merged**
